# Generated by Django 5.1.2 on 2024-11-10 20:43

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('birth_date', models.DateField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('type', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='NotStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('type', models.CharField(choices=[('Informática', 'Informática'), ('Logística', 'Logística')], max_length=11)),
                ('shift', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_years', to='api.class')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.CharField(max_length=2000)),
                ('fixed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcemets', to='api.classyear')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.notstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=9)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.parent')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ClassYearTeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classyear')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_year_teacher_subject', to='api.teachersubject')),
            ],
            options={
                'unique_together': {('class_year', 'teacher_subject')},
            },
        ),
        migrations.AddField(
            model_name='classyear',
            name='teacher_subject',
            field=models.ManyToManyField(related_name='class_year', through='api.ClassYearTeacherSubject', to='api.teachersubject'),
        ),
        migrations.CreateModel(
            name='TimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(18)])),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classyear')),
                ('friday_class_year_teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='api.classyearteachersubject')),
                ('monday_class_year_teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='api.classyearteachersubject')),
                ('thursday_class_year_teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='api.classyearteachersubject')),
                ('tuesday_class_year_teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='api.classyearteachersubject')),
                ('wednesday_class_year_teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='api.classyearteachersubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'class_year')},
            },
        ),
        migrations.AddField(
            model_name='classyear',
            name='students',
            field=models.ManyToManyField(related_name='class_year', through='api.StudentClass', to='api.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', through='api.TeacherSubject', to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av1_1', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('av2_1', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('noa_1', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('av1_2', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('av2_2', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('noa_2', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('av1_3', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('av2_3', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('noa_3', models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True)),
                ('year', models.PositiveIntegerField()),
                ('degree', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.teachersubject')),
            ],
            options={
                'unique_together': {('student', 'year', 'degree', 'teacher_subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classyear',
            unique_together={('_class', 'year')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FALTA', 'FALTA'), ('JUSTIFICADA', 'JUSTIFICADA'), ('PRESENTE', 'PRESENTE')], max_length=11)),
                ('day', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_year_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classyearteachersubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'class_year_teacher_subject', 'day')},
            },
        ),
    ]
