# Generated by Django 5.1 on 2024-10-06 01:12

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'year', 'degree', 'unit', 'teacher_subject')},
        ),
        migrations.AddField(
            model_name='grade',
            name='av1_1',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='av1_2',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='av1_3',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='av2_1',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='av2_2',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='av2_3',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='noa_1',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='noa_2',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='noa_3',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('PA', 'PA'), ('A', 'A')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', through='api.TeacherSubject', to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='type',
        ),
    ]
