# Generated by Django 5.1 on 2024-10-08 20:18

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_grade_unique_together_grade_av1_1_grade_av1_2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'year', 'degree', 'teacher_subject')},
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('Informática', 'Informática'), ('Logística', 'Logística')], max_length=11),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='unit',
        ),
    ]
