# Generated by Django 5.1 on 2024-09-21 19:14

import api.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_class_degree_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='timeschedule',
            name='day',
            field=models.CharField(choices=[('SEGUNDA', 'SEGUNDA'), ('TERCA', 'TERCA'), ('QUARTA', 'QUARTA'), ('QUINTA', 'QUINTA'), ('SEXTA', 'SEXTA'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=7),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FALTA', 'FALTA'), ('JUSTIFICADA', 'JUSTIFICADA'), ('PRESENTE', 'PRESENTE')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_year_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.classyearteachersubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendances', to='api.student')),
            ],
        ),
    ]
