# Generated by Django 5.1 on 2024-09-14 02:35

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_classteachersubject_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='unit',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.DeleteModel(
            name='TimeSchedule',
        ),
    ]
