# Generated by Django 5.1 on 2024-09-21 19:54

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_birth_date_user_end_date_user_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
