# Generated by Django 5.1 on 2024-09-14 20:10

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_class_degree_alter_grade_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='unit',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
    ]
