# Generated by Django 5.1.2 on 2024-10-26 02:40

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_class_degree'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_year_teacher_subject', 'created_at')},
        ),
    ]
