# Generated by Django 5.1.2 on 2024-10-26 03:01

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_managers_attendance_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_year_teacher_subject', 'day')},
        ),
    ]
