# Generated by Django 5.1.2 on 2024-10-27 07:07

import api.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_class_degree_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='class_year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.classyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='friday_class_year_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='api.classyearteachersubject'),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='monday_class_year_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='api.classyearteachersubject'),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='thursday_class_year_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='api.classyearteachersubject'),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='tuesday_class_year_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='api.classyearteachersubject'),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='wednesday_class_year_teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='api.classyearteachersubject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='class_year_teacher_subject',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='day',
        ),
    ]
