# Generated by Django 5.1.2 on 2024-10-27 07:08

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_timeschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
        migrations.AlterUniqueTogether(
            name='timeschedule',
            unique_together={('hour', 'minute', 'class_year')},
        ),
    ]
