# Generated by Django 5.1.2 on 2024-10-27 07:58

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_class_degree_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeschedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.IntegerField(validators=[api.utils.validate_range]),
        ),
    ]
